---
title: "Chapter14.5"
author: "Megan Bontrager"
date: "6/22/2020"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code from book chapter 14.5


```{r, cache = TRUE}
library(rethinking)
data("islandsDistMatrix")
Dmat = islandsDistMatrix

colnames(Dmat) = c("Ml", "Ti", "SC", "Ya", "Fi", "Tr", "Ch", "Mn", "To", "Ha")
round(Dmat, 1)

# compare linear and exponential decay
curve(exp(-1*x), from = 0, to  = 4)
curve(exp(-1*x^2), from = 0, to  = 4, add = TRUE, lty = 2)

data("Kline2")

d = Kline2
d$society = 1:10

dat_list = list(T = d$total_tools,
                P = d$population,
                society = d$society,
                Dmat = islandsDistMatrix)

m14.7 = ulam(
  alist(
    T ~ dpois(lambda),
    lambda <- (a*P^b/g)*exp(k[society]),
    vector[10]:k ~ multi_normal(0, SIGMA),
    matrix[10, 10]:SIGMA <- cov_GPL2(Dmat, etasq, rhosq, 0.01),
    c(a,b,g) ~ dexp(1),
    etasq ~ dexp(2),
    rhosq ~ dexp(0.5)
  ), data = dat_list, chains = 4, cores = 4, iter = 2000, log_lik = TRUE)
    
precis(m14.7, depth = 3)

post = extract.samples(m14.7)

plot(NULL, xlab = "distance", ylab = "cov", xlim = c(0,10), ylim = c(0,2))

x_seq = seq(from = 0, to = 10, length.out = 100)
pmcov = sapply(x_seq, function(x) post$etasq*exp(-post$rhosq*x^2))
pmcov_mu = apply(pmcov, 2, mean)
lines(x_seq, pmcov_mu, lwd = 2)

for (i in 1:50)
  curve(post$etasq[i]*exp(-post$rhosq[i]*x^2), add = TRUE, col = col.alpha("black", 0.3))

K = matrix(0, nrow = 10, ncol = 10)

for(i in 1:10)
  for(j in 1:10)
    K[i,j] = median(post$etasq)*exp(-median(post$rhosq)*islandsDistMatrix[i,j]^2)
diag(K) = median(post$etasq) + 0.01

round(K, 2)

Rho = round(cov2cor(K), 2)

colnames(Rho) = c("Ml", "Ti", "SC", "Ya", "Fi", "Tr", "Ch", "Mn", "To", "Ha")
rownames(Rho) = colnames(Rho)
Rho

psize = d$logpop/max(d$logpop)
psize = exp(psize*1.5) - 2

plot(d$lon2, d$lat, xlab = "long", ylab = "lat", col = rangi2, cex = psize, pch = 16, xlim = c(-50, 30))
labels = as.character(d$culture)
text(d$lon2, d$lat, labels = labels, cex = 0.7, pos = c(2, 4, 3, 3, 4, 1, 3, 2, 4, 2))

for(i in 1:10)
  for(j in 1:10)
    if(i < j)
      lines(c(d$lon2[i], d$lon2[j]), c(d$lat[i], d$lat[j]), 
            lwd = 2, col = col.alpha("black", Rho[i,j]^2))

logpop.seq = seq(from = 6, to = 14, length.out = 30)

lambda = sapply(logpop.seq, function(lp) post$a*exp(lp)^post$b/post$g)
lambda.median = apply(lambda, 2, median)
lambda.PI80 = apply(lambda, 2, PI, prob = 0.8)

plot(d$logpop, d$total_tools, col = rangi2, cex = psize, pch = 16, xlab = "log pop", ylab = "tools")
text(d$logpop, d$total_tools, labels = labels, cex = 0.7, pos = c(4,3,4,2,2,1,4,4,4,2))

lines(logpop.seq, lambda.median, lty = 2)
lines(logpop.seq, lambda.PI80[1,], lty = 2)
lines(logpop.seq, lambda.PI80[2,], lty = 2)

for(i in 1:10)
  for(j in 1:10)
    if(i < j)
      lines(c(d$logpop[i], d$logpop[j]), 
            c(d$total_tools[i], d$total_tools[j]),
            lwd = 2, col = col.alpha("black", Rho[i,j])
              )
# colnames(Rho) = c("Ml", "Ti", "SC", "Ya", "Fi", "Tr", "Ch", "Mn", "To", "Ha")

```

Now need to generate old model to compare:

```{r, cache=TRUE}
d$cid = ifelse(d$contact == "high", 2, 1)

dat2 = list(T = d$total_tools, P = d$population, cid = d$cid)

m11.11 = ulam(
  alist(T ~ dpois(lambda),
        lambda <- exp(a[cid])*P^b[cid]/g,
        a[cid] ~ dnorm(1,1),
        b[cid] ~ dexp(1),
        g ~ dexp(1)),
  data = dat2, chains = 4, log_lik = TRUE)

precis(m11.11, depth = 2)
precis(m14.7, depth = 2)

WAIC(m11.11)
WAIC(m14.7)

compare(m11.11, m14.7)

```

